name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/yarn
          node_modules
          front-end/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Backend Dependencies
      run: |
        rm -f package-lock.json
        yarn install --frozen-lockfile

    - name: Install Frontend Dependencies
      working-directory: front-end
      run: |
        rm -f package-lock.json
        yarn install --frozen-lockfile

    - name: Build Frontend
      working-directory: front-end
      run: yarn build

    - name: Run Backend Tests
      run: yarn test

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: front-end/build/
