name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          node_modules
          front-end/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', 'package.json', 'front-end/package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Configure Yarn
      run: |
        npm install -g yarn
        yarn config set registry https://registry.npmmirror.com
        yarn config set network-timeout 600000
        yarn config set network-concurrency 1
        yarn config set strict-ssl false
        npm config set strict-ssl false
        yarn config set retry-times 5
        yarn config set retry-interval 5000

    - name: Install Backend Dependencies
      run: |
        yarn install --network-timeout 600000
      if: steps.yarn-cache.outputs.cache-hit != 'true'

    - name: Install Frontend Dependencies
      working-directory: front-end
      run: |
        yarn install --network-timeout 600000
      if: steps.yarn-cache.outputs.cache-hit != 'true'

    - name: Build Frontend
      working-directory: front-end
      run: yarn build
      env:
        CI: true

    - name: Run Tests
      run: yarn test
      env:
        CI: true

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: front-end/build/
        if-no-files-found: error
